# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  Gibbs 
#' @description  Gibbs 
#' @param N int
#' @param thin int
#' @return mat \code{n}
#' @export
gibbsC <- function(N, thin) {
    .Call('_SA24204183_gibbsC', PACKAGE = 'SA24204183', N, thin)
}

#' @title Rcpp test
#' @description test
#' @param x int
#' @param y int
#' @return max \code{n}
#' @export
max <- function(x, y) {
    .Call('_SA24204183_max', PACKAGE = 'SA24204183', x, y)
}

